# Generated by Django 2.0.4 on 2018-04-29 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('origen', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('foto', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('kilometraje', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portalAutomotora.Auto')),
            ],
        ),
        migrations.CreateModel(
            name='tipoAuto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='auto',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portalAutomotora.Marca'),
        ),
        migrations.AddField(
            model_name='auto',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portalAutomotora.Modelo'),
        ),
        migrations.AddField(
            model_name='auto',
            name='tipoAuto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portalAutomotora.tipoAuto'),
        ),
    ]
