# Generated by Django 2.0.4 on 2018-04-29 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portalAutomotora', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='modelo',
        ),
        migrations.AddField(
            model_name='modelo',
            name='marca',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='portalAutomotora.Marca'),
            preserve_default=False,
        ),
    ]
